language: ruby
addons:
  ssh_known_hosts: kill-the-newsletter.com
before_deploy:
  - openssl aes-256-cbc -K $encrypted_665aea1b3ddf_key -iv $encrypted_665aea1b3ddf_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
deploy:
  provider: script
  script: bash deploy.sh
